// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class File
{
    public string ID { get; set; }

    public string Type { get; set; }

    public string Name { get; set; }

    public long Size { get; set; }

    public string Path { get; set; }
}