// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class Language
{
    public string ID { get; set; }

    public long Seq { get; set; }

    public long IsEnabled { get; set; }

    public virtual ICollection<MenuTranslation> MenuTranslation { get; } = new List<MenuTranslation>();
}