// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class vwMenu
{
    public string ID { get; set; }

    public string PID { get; set; }

    public string IDs { get; set; }

    public long? Seq { get; set; }

    public long? Depth { get; set; }
}